name: GovComGPTQ
channels:
  - pytorch
  - nvidia/label/cuda-12.1.0
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - appdirs=1.4.4=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.0.9=py311h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.12.31=h06a4308_0
  - cairo=1.16.0=hf32fb01_1
  - certifi=2024.12.14=py311h06a4308_0
  - cffi=1.17.1=py311hf29c0ef_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py311h06a4308_0
  - cssselect2=0.2.1=pyh9f0ad1d_1
  - cuda=11.8.0=0
  - cuda-cccl=12.1.55=0
  - cuda-cccl_linux-64=12.6.77=ha770c72_0
  - cuda-command-line-tools=11.8.0=0
  - cuda-compiler=12.1.0=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cudart-static=12.6.77=h5888daf_0
  - cuda-cudart-static_linux-64=12.6.77=h3f2d84a_0
  - cuda-cuobjdump=12.1.55=0
  - cuda-cupti=12.1.105=0
  - cuda-cupti-static=12.6.80=ha770c72_0
  - cuda-cuxxfilt=12.1.55=0
  - cuda-demo-suite=12.1.55=0
  - cuda-documentation=12.1.55=0
  - cuda-driver-dev=12.1.55=0
  - cuda-gdb=12.1.55=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.6.2=0
  - cuda-libraries-static=12.1.0=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.1.55=0
  - cuda-nsight-compute=12.1.0=0
  - cuda-nvcc=12.1.66=0
  - cuda-nvdisasm=12.1.55=0
  - cuda-nvml-dev=12.1.55=0
  - cuda-nvprof=12.1.55=0
  - cuda-nvprune=12.1.55=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvrtc-static=12.6.85=h5888daf_0
  - cuda-nvtx=12.1.105=0
  - cuda-nvvp=12.1.55=0
  - cuda-opencl=12.1.56=0
  - cuda-opencl-dev=12.1.56=0
  - cuda-profiler-api=12.1.55=0
  - cuda-runtime=12.1.0=0
  - cuda-sanitizer-api=12.1.55=0
  - cuda-toolkit=11.8.0=0
  - cuda-tools=11.8.0=0
  - cuda-version=12.6=3
  - cuda-visual-tools=12.1.0=0
  - expat=2.6.4=h5888daf_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py311h06a4308_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.13.1=h6c09931_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.55.3=py311h2dc5d0c_1
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h36c2ea0_0
  - gds-tools=1.6.0.25=0
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.2=h5eee18b_0
  - glib=2.68.4=h9c3ff4c_1
  - glib-tools=2.68.4=h9c3ff4c_1
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.13=h58526e2_1001
  - harfbuzz=3.0.0=h83ec7ef_1
  - html5lib=1.1=pyhd8ed1ab_2
  - icu=68.2=h9c3ff4c_0
  - idna=3.7=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py311h06a4308_1
  - joblib=1.4.2=py311h06a4308_0
  - jpeg=9e=h5eee18b_3
  - kaleido-core=0.2.1=h3644ca4_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcublas=12.1.0.26=0
  - libcublas-dev=11.11.3.6=0
  - libcublas-static=12.6.4.1=h5888daf_0
  - libcufft=11.0.2.4=0
  - libcufft-dev=10.9.0.58=0
  - libcufft-static=11.3.0.4=h5888daf_0
  - libcufile=1.11.1.6=0
  - libcufile-dev=1.6.0.25=0
  - libcufile-static=1.6.0.25=0
  - libcurand=10.3.7.77=0
  - libcurand-dev=10.3.2.56=0
  - libcurand-static=10.3.2.56=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.1.48=0
  - libcusolver-static=11.7.1.2=h5888daf_0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=11.7.5.86=0
  - libcusparse-static=12.5.4.2=h5888daf_0
  - libdeflate=1.22=h5eee18b_0
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.68.4=h174f98d_1
  - libgomp=14.2.0=h77fa898_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=11.8.0.86=0
  - libnpp-static=12.3.1.54=h5888daf_0
  - libnvfatbin=12.6.77=hbd13f7d_0
  - libnvfatbin-dev=12.6.77=h5888daf_0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.55=0
  - libnvjitlink-static=12.6.85=h5888daf_0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=11.9.0.86=0
  - libnvjpeg-static=12.3.3.54=ha770c72_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h8a09558_0
  - libxml2=2.9.12=h72842e0_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py311h5eee18b_1
  - mathjax=2.7.7=ha770c72_3
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_2
  - mkl_fft=1.3.11=py311h5eee18b_0
  - mkl_random=1.2.8=py311ha02d727_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.3=py311h06a4308_0
  - nsight-compute=2023.1.0.15=0
  - nspr=4.36=h5888daf_0
  - nss=3.69=hb5efdd6_1
  - numpy=1.24.3=py311h08b1b3b_1
  - numpy-base=1.24.3=py311hf175353_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.4.0=h7b32b05_1
  - packaging=24.2=py311h06a4308_0
  - pandas=2.2.1=py311h1128e8f_0
  - pango=1.48.10=h54213e6_2
  - pcre=8.45=h9c3ff4c_0
  - pillow=11.0.0=py311hcea889d_1
  - pip=24.2=py311h06a4308_0
  - pixman=0.44.2=h29eaf8c_0
  - psutil=5.9.0=py311h5eee18b_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycparser=2.22=pyh29332c3_1
  - pydyf=0.11.0=pyhd8ed1ab_1
  - pyphen=0.17.0=pyhd8ed1ab_1
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.5=h955ad1f_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-kaleido=0.2.1=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytorch=2.2.1=py3.11_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_6
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py311h06a4308_0
  - pyyaml=6.0.2=py311h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py311h06a4308_1
  - scikit-learn=1.5.2=py311h6a678d5_0
  - scipy=1.14.1=py311h08b1b3b_0
  - setuptools=72.1.0=py311h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py311h92b7b1e_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.2.1=py311_cu121
  - torchtriton=2.2.0=py311
  - torchvision=0.17.1=py311_cu121
  - tqdm=4.66.5=py311h92b7b1e_0
  - typing_extensions=4.12.2=py311h06a4308_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py311h9ecbd09_1
  - urllib3=2.2.3=py311h06a4308_0
  - weasyprint=62.3=pyhd8ed1ab_1
  - webencodings=0.5.1=pyhd8ed1ab_3
  - wheel=0.44.0=py311h06a4308_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - attrs==24.3.0
      - auto-gptq==0.7.1
      - blinker==1.9.0
      - cloudpickle==3.1.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - dash-mantine-components==0.11.1
      - datasets==3.2.0
      - dill==0.3.8
      - fastjsonschema==2.21.1
      - flash-attention==1.0.0
      - flash-attn==2.7.3
      - flask==3.0.3
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gekko==1.2.1
      - importlib-metadata==8.5.0
      - iniconfig==2.0.0
      - itsdangerous==2.2.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-core==5.7.2
      - kiwisolver==1.4.8
      - matplotlib==3.10.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - patsy==1.0.1
      - peft==0.6.0
      - platformdirs==4.3.6
      - plotly==5.24.1
      - pluggy==1.5.0
      - propcache==0.2.1
      - pyarrow==18.1.0
      - pyparsing==3.2.1
      - referencing==0.35.1
      - regex==2024.11.6
      - rouge==1.0.1
      - rpds-py==0.22.3
      - sentence-transformers==3.1.0
      - sentencepiece==0.2.0
      - statsmodels==0.14.4
      - sympy==1.13.1
      - tenacity==9.0.0
      - tokenizers==0.20.3
      - traitlets==5.14.3
      - transformers==4.45.0
      - transforms==0.2.1
      - werkzeug==3.0.6
      - wrapt==1.17.1
      - xxhash==3.5.0
      - yarl==1.18.3
      - zipp==3.21.0
prefix: /home/overven/.conda/envs/GovComGPTQ